global:
  scrape_interval: 5s
scrape_configs:
  - job_name: llm-service
    metrics_path: /metrics
    static_configs:
      - targets:
          # If your app runs on your Mac host at :8000
          - host.docker.internal:8000